package ast

type NodeType string

const (
	EmptyNode   NodeType = "Empty"
	ProgramNode NodeType = "Program"
	TextNode    NodeType = "Text"
	// Expressions
	ArrayLiteralExpr       NodeType = "ArrayLiteralExpression"
	BinaryOpExpr           NodeType = "BinaryOpExpression"
	CastExpr               NodeType = "CastExpression"
	CoalesceExpr           NodeType = "CoalesceExpression"
	CompoundAssignmentExpr NodeType = "CompoundAssignmentExpression"
	ConditionalExpr        NodeType = "ConditionalExpression"
	ConstantAccessExpr     NodeType = "ConstantAccessExpression"
	EmptyIntrinsicExpr     NodeType = "EmptyIntrinsicExpression"
	EqualityExpr           NodeType = "EqualityExpression"
	ExitIntrinsicExpr      NodeType = "ExitIntrinsicExpression"
	FloatingLiteralExpr    NodeType = "FloatingLiteralExpression"
	FunctionCallExpr       NodeType = "FunctionCallExpression"
	IncludeExpr            NodeType = "IncludeExpression"
	IncludeOnceExpr        NodeType = "IncludeOnceExpression"
	IntegerLiteralExpr     NodeType = "IntegerLiteralExpression"
	IssetIntrinsicExpr     NodeType = "IssetIntrinsicExpression"
	LogicalNotExpr         NodeType = "LogicalNotExpression"
	ParenthesizedExpr      NodeType = "ParenthesizedExpression"
	PostfixIncExpr         NodeType = "PostfixIncExpression"
	PrefixIncExpr          NodeType = "PrefixIncExpression"
	PrintExpr              NodeType = "PrintExpression"
	RelationalExpr         NodeType = "RelationalExpression"
	RequireExpr            NodeType = "RequireExpression"
	RequireOnceExpr        NodeType = "RequireOnceExpression"
	ShiftExpr              NodeType = "ShiftExpression"
	SimpleAssignmentExpr   NodeType = "SimpleAssignmentExpression"
	SimpleVariableExpr     NodeType = "SimpleVariableExpression"
	StringLiteralExpr      NodeType = "StringLiteralExpression"
	SubscriptExpr          NodeType = "SubscriptExpression"
	UnaryOpExpr            NodeType = "UnaryOpExpression"
	UnsetIntrinsicExpr     NodeType = "UnsetIntrinsicExpression"
	VariableNameExpr       NodeType = "VariableNameExpression"
	// Statements
	CompoundStmt           NodeType = "CompoundStatement"
	ConstDeclarationStmt   NodeType = "ConstDeclarationStatement"
	EchoStmt               NodeType = "EchoStatement"
	ExpressionStmt         NodeType = "ExpressionStatement"
	ForStmt                NodeType = "ForStatement"
	FunctionDefinitionStmt NodeType = "FunctionDefinitionStatement"
	IfStmt                 NodeType = "IfStatement"
	WhileStmt              NodeType = "WhileStatement"
	DoStmt                 NodeType = "DoStatement"
	ReturnStmt             NodeType = "ReturnStatement"
	ContinueStmt           NodeType = "ContinueStatement"
	BreakStmt              NodeType = "BreakStatement"
)
