name: Official PHP Tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  test-linux:
    name: Build & Run official PHP Tests on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.24
      uses: actions/setup-go@v6
      with:
        go-version: ^1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Download php-src repository
      run: git clone https://github.com/php/php-src.git --depth 1

    - name: Building
      run: go build -v -o . ./...

    - name: Testing against official PHP Tests
      run: ./qiqTester -v2 php-src/tests

  windows-linux:
    name: Build & Run official PHP Tests on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.24
      uses: actions/setup-go@v6
      with:
        go-version: ^1.24

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Download php-src repository
      run: git clone https://github.com/php/php-src.git --depth 1

    - name: Building
      run: go build -v -o . ./...

    - name: Testing against official PHP Tests
      run: .\qiqTester.exe -v2 php-src\tests